[project]
name = "gcode2dplotterart"
version = "0.0.1"
description = "Easily generate plotter art with your 2D Plotter or 3D Printer. This library abstracts away G-Code so you can focus on making art."
authors = [
  { name="Travis Bumgarner", email="travis@sillysideprojects.com" },
]

[build-system]
requires = ["hatchling", "setuptools", "wheel"]
build-backend = "hatchling.build"

[tool.poetry.dependencies]
python = "^3.11.5"
mypy="^1.7.0"
black="^23.10.1"
flake8="^6.1.0"
pytest="^7.4.3"
matplotlib="^3.8.1"
numpy="^1.26.1"
setuptools = "^68.2.2"
wheel = "^0.41.3"

[project.urls]
"Homepage" = "https://github.com/TravisBumgarner/gcode2dplotterart"
"Bug Tracker" = "https://github.com/TravisBumgarner/gcode2dplotterart/issues"